### PR TITLE
Add orange colour variations

### PR DESCRIPTION
**Pull request by Amwam**
Screenshot 2019-08-09 at 17 20 51

### CODE REVIEW

**Comment by rrees** [comment]
It would be helpful to know where these are used or what they are intended for

**Comment by Amwam** [comment]
@rrees orange-main will be used on the compliance reports. The rest are just for consistency as far as I'm aware.

**Comment by rrees** [comment]
Are they warning colours? It would be good to have a bit more information for people than just providing a colour spectrum.

**Comment by Amwam** [comment]
Yeah to represent somewhere in between warning and danger

**Pull request merged**
